---
title: "Project 1 Final report"
author: Shuai Zhu
date: "`r Sys.Date()`"
output: 
  pdf_document:
    latex_engine: pdflatex
    keep_tex: true
    number_sections: true
    fig_caption: true
fontsize: 12pt
geometry: "margin=1in"
header-includes:
   - \usepackage{setspace}
   #- \onehalfspacing
   - \doublespacing
---
<style>
  body {
    font-family: Arial, sans-serif;
  }
</style>


# Introduction

To understand the effect of physical activity on 7-year all-cause mortality, the proposed grant application outlines a randomized trial to investigate a novel intervention called “ACTUP.” This intervention is designed to increase physical activity by a fixed 30% (individual-specific) among sedentary older adults. Participants will be asked to wear wrist-worn accelerometers for 7 days to objectively measure their physical activity levels. Activity will be evaluated using the Total Monitor Independent Movement Summary (TMIMS), calculated as the mean value over the 7-day period. 

The study has two primary aims. First Aim is to determine whether the ACTUP intervention leads to a reduction in the risk of 7-year all-cause mortality (the primary endpoint) in sedentary adults aged 60-75 at the group-average level. The second Aim is to explore whether the efficacy of the ACTUP intervention is moderated by gender, assessing if there are gender-specific differences in the treatment effect.

# Method
## data cleaning
Data were filtered to include participants aged between 60 and 75. Sedentary status was defined as being below the 25th percentile of the total MIMS distribution. Participants with a follow-up time of less than 7 years were excluded from the analysis. For this analysis, individuals who died after 7 years from the start of the study were considered alive.

## data analysis

For Aim 1, we will test whether the ACTUP intervention leads to a reduction in the risk of 7-year all-cause mortality in sedentary adults aged 60-75 using a logistic regression model. The binary outcome will be whether the individual died within the 7-year follow-up period, and the primary predictor will be the treatment group (ACTUP vs. control).

To simulate differences in mortality, the coefficient for gender from a logistic regression model using the NHANES dataset will be utilized. This model will have mortality as the outcome and gender as the predictor. The simulated data will include sample sizes ranging from 100 to 2000, increasing in increments of 100. Each simulated sample will maintain a 1:1 ratio of men to women and a 1:1 ratio of control to treatment groups. The simulated data will then be fitted to a multiple variable logistic regression model, with mortality as the outcome and treatment and gender as predictors. This process will be repeated 10,000 times, and the power will be calculated as the proportion of iterations that yield a statistically significant result, divided by 10,000.

To evaluate whether the efficacy of the ACTUP intervention is moderated by gender, a second logistic regression model will be used, with mortality as the outcome and treatment, gender, and their interaction term as predictors. This model will help assess if there are significant gender-specific differences in treatment effect.

For both aims, we will estimate the sample size required to achieve 80% statistical power at a significance level of 0.05.

