---
title: "Project 2 Final report"
author: Shuai Zhu
date: "`r Sys.Date()`"
fontsize: 12pt
geometry: "margin=1in"
mainfont: Times New Roman
output:
  pdf_document:
    latex_engine: pdflatex
    keep_tex: false
    number_sections: true
    fig_caption: true
header-includes:
  - \usepackage{setspace}
  - \doublespacing
---
# INTRODUCTION

To understand the effect of physical activity on 7-year all-cause mortality, the proposed grant application outlines a randomized trial to investigate a novel intervention called “ACTUP.” This intervention is designed to increase physical activity by a fixed 30% (individual-specific) among sedentary older adults. Participants will be asked to wear wrist-worn accelerometers for 7 days to objectively measure their physical activity levels. Activity will be evaluated using the Total Monitor Independent Movement Summary (TMIMS), calculated as the mean value over the 7-day period. 

The study has two primary aims. First Aim is to determine whether the ACTUP intervention leads to a reduction in the risk of 7-year all-cause mortality (the primary endpoint) in sedentary adults aged 60-75 at the group-average level. The second Aim is to explore whether the efficacy of the ACTUP intervention is moderated by gender, assessing if there are gender-specific differences in the treatment effect.


# METHOD
# RESULTS
# APPENDIX








